[package]
name = "store-backend"
version = "0.1.0"
authors = ["Muhammad Anjum Kaiser <anjumbutt@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
hyper = "*"
hyper-native-tls = "*"
params = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
toml = "*"
postgres = "*"
diesel = "*"
diesel_codegen="*"
dotenv = "*"
r2d2 = "*"
r2d2_postgres = "*"
r2d2-diesel="*"
