[package]
name = "store-backend"
version = "0.1.0"
authors = ["Muhammad Anjum Kaiser <anjumbutt@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
hyper = "*"
serde = "*"
serde_json = "*"
toml = "*"