[package]
authors = ["Muhammad Anjum Kaiser <anjumbutt@gmail.com>"]
name = "store-backend"
version = "0.1.0"

[dependencies]
diesel_codegen = "0.11.0"
dotenv = "0.8.0"
hyper = "0.10.5"
hyper-native-tls = "0.2.2"
iron = "0.5.1"
iron-csrf = "0.0.10"
params = "0.6.0"
persistent = "0.3.0"
postgres = "0.14.0"
r2d2 = "0.7.1"
r2d2-diesel = "0.11.0"
r2d2_postgres = "0.12.0"
r2d2_redis = "0.6.0"
redis = "0.8.0"
router = "0.5.1"
serde = "0.9.10"
serde_derive = "0.9.10"
serde_json = "0.9.8"
toml = "0.3.1"

[dependencies.diesel]
features = ["postgres"]
version = "0.11"
