[package]
authors = ["Muhammad Anjum Kaiser <anjumbutt@gmail.com>"]
name = "store-backend"
version = "0.1.0"

[dependencies]
bincode = "0.8.0"
bson = "0.8.0"
dotenv = "0.10.0"
hyper = "0.10.5"
hyper-native-tls = "0.2.2"
iron = "0.5.1"
params = "0.6.0"
persistent = "0.3.0"
r2d2 = "0.7.2"
r2d2-diesel = "0.13.0"
r2d2_postgres = "0.12.0"
r2d2_redis = "0.6.0"
redis = "0.8.0"
rmp-serde = "0.13.3"
router = "0.5.1"
serde = "1.0"
serde_cbor = "0.6.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5.1"
serde_xml = "0.9.1"
serde_yaml = "0.7.1"
toml = "0.4.0"
uuid = "0.4.0"
time = "0.1"

[dependencies.postgres]
features = ["with-uuid", "with-time"]
version = "0.14.0"

[dependencies.diesel]
features = ["postgres", "uuid", "serde_json"]
version = "0.13.0"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.13.0"
